"""initial schema

Revision ID: a685bb03e168
Revises: 
Create Date: 2026-01-18 23:41:46.890408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'a685bb03e168'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
     # Pastikan extension yang dibutuhkan ada
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('document_status',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('listing_boards',
    sa.Column('code', sa.CHAR(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('issuers',
    sa.Column('code', sa.CHAR(length=10), nullable=False),
    sa.Column('listing_board_code', sa.CHAR(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['listing_board_code'], ['listing_boards.code'], ),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('collection_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('issuer_code', sa.CHAR(length=10), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('publish_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_code'], ['collections.code'], ),
    sa.ForeignKeyConstraint(['issuer_code'], ['issuers.code'], ),
    sa.ForeignKeyConstraint(['status'], ['document_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_table('slides',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_text_vector', pgvector.sqlalchemy.Vector(dim=1024), nullable=True),
    sa.Column('content_base_64', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slides')
    op.drop_table('documents')
    op.drop_table('issuers')
    op.drop_table('listing_boards')
    op.drop_table('document_status')
    op.drop_table('collections')
    # ### end Alembic commands ###
